# Generated by Django 5.1.5 on 2025-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('audio_url', models.URLField(blank=True, help_text='Link to audio file', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Link to video file', null=True)),
            ],
        ),
    ]
