# Generated by Django 5.1.5 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0004_meditationsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
