# Generated by Django 5.1.5 on 2025-03-19 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0005_meditationsession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='session_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
